### ISSUE TITLE
Get Not compatible with the version of your running IDE (WebStorm 2023.1.2)

### ISSUE THREAD

**Issue by arentalb** [Flyrell/html-attribute-folder#4]
i try to dawnload the plugin but it is not compatible

**Comment by tscharke** [comment]
I stumbled across this plugin recently and got it working again 💪

For this I created a [fork](https://github.com/tscharke/html-attribute-folder) and make it runnable 👉[https://github.com/tscharke/html-attribute-folder](https://github.com/tscharke/html-attribute-folder)

Or vote for this PR #5, so that @Flyrell integrates it 😃

**Comment by arentalb** [comment]
good
